# Generated by Django 4.2.13 on 2025-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songs_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
